#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-i18n
Version  : 0.7.0
Release  : 6
URL      : https://rubygems.org/downloads/i18n-0.7.0.gem
Source0  : https://rubygems.org/downloads/i18n-0.7.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
# Ruby I18n
[![Build Status](https://api.travis-ci.org/svenfuchs/i18n.svg?branch=master)](https://travis-ci.org/svenfuchs/i18n)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n i18n-0.7.0
gem spec %{SOURCE0} -l --ruby > rubygem-i18n.gemspec

%build
gem build rubygem-i18n.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
i18n-0.7.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/i18n-0.7.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/gemfiles/Gemfile.rails-3.2.x
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/gemfiles/Gemfile.rails-3.2.x.lock
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/gemfiles/Gemfile.rails-4.0.x
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/gemfiles/Gemfile.rails-4.0.x.lock
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/gemfiles/Gemfile.rails-4.1.x
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/gemfiles/Gemfile.rails-4.1.x.lock
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/gemfiles/Gemfile.rails-4.2.x
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/gemfiles/Gemfile.rails-4.2.x.lock
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/gemfiles/Gemfile.rails-master
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/gemfiles/Gemfile.rails-master.lock
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/backend.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/backend/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/backend/cache.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/backend/cascade.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/backend/chain.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/backend/fallbacks.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/backend/flatten.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/backend/gettext.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/backend/interpolation_compiler.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/backend/key_value.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/backend/memoize.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/backend/metadata.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/backend/pluralization.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/backend/simple.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/backend/transliterator.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/config.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/core_ext/hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/core_ext/kernel/suppress_warnings.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/core_ext/string/interpolate.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/exceptions.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/gettext.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/gettext/helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/gettext/po_parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/interpolate/ruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/locale.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/locale/fallbacks.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/locale/tag.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/locale/tag/parents.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/locale/tag/rfc4646.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/locale/tag/simple.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/tests.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/tests/basics.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/tests/defaults.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/tests/interpolation.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/tests/link.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/tests/localization.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/tests/localization/date.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/tests/localization/date_time.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/tests/localization/procs.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/tests/localization/time.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/tests/lookup.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/tests/pluralization.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/tests/procs.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/lib/i18n/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/api/all_features_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/api/cascade_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/api/chain_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/api/fallbacks_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/api/key_value_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/api/memoize_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/api/override_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/api/pluralization_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/api/simple_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/backend/cache_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/backend/cascade_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/backend/chain_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/backend/exceptions_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/backend/fallbacks_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/backend/interpolation_compiler_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/backend/key_value_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/backend/memoize_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/backend/metadata_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/backend/pluralization_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/backend/simple_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/backend/transliterator_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/core_ext/hash_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/gettext/api_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/gettext/backend_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/i18n/exceptions_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/i18n/interpolate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/i18n/load_path_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/i18n_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/locale/fallbacks_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/locale/tag/rfc4646_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/locale/tag/simple_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/run_all.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/test_data/locales/de.po
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/test_data/locales/en.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/test_data/locales/en.yml
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/test_data/locales/invalid/empty.yml
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/test_data/locales/invalid/syntax.yml
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/test_data/locales/plurals.rb
/usr/lib64/ruby/gems/2.3.0/gems/i18n-0.7.0/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/specifications/i18n-0.7.0.gemspec
